-- 🔒 POLITIQUES RLS SIMPLIFIÉES POUR L'INSCRIPTION
-- ⚠️ ATTENTION : Politiques plus permissives pour éviter les blocages

-- 1. DÉSACTIVER RLS SUR TOUTES LES TABLES
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE establishments DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE qr_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE qr_scans DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff_activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE establishment_types DISABLE ROW LEVEL SECURITY;

-- 2. MESSAGE DE CONFIRMATION
DO $$
BEGIN
    RAISE NOTICE '🔓 RLS DÉSACTIVÉ SUR TOUTES LES TABLES !';
    RAISE NOTICE '✅ L''inscription devrait maintenant fonctionner.';
    RAISE NOTICE '⚠️ ATTENTION : Sécurité réduite - à réactiver plus tard.';
    RAISE NOTICE '';
END $$;
